### ISSUE TITLE
ConfirmDialog sollte loading prop aufnehmen

### ISSUE THREAD

**Issue by johannessteu** [t3n/react-packages#281]
Wenn man den Confirm-Dialog nutzt kann es sein, dass man einen Loading indicator benötigt damit der User sieht das etwas passeirt ehe das Modal dann schließt.
In der Zeit wo loading true ist sollte der Confirm-Button dann im loading state sein

**Comment by birterohden** [comment]
Solved siehe [hier](https://github.com/t3n/react-packages/commit/9e26a61aa8f142f04eddf858af4f505db45aa409)
